### ISSUE TITLE
Cannot read property 'id' of undefined - react-modal: No elements were found for selector .app.

### ISSUE THREAD

**Issue by dgoumans** [stripe/stripe-demo-connect-kavholm-marketplace#8]
Did a fresh pull, configured my .env and used _npm install_, _npm run dev_ to start the app.
Sign-in and using the /listings/ page works fine. Once I jump to the /listings/[id] (e.g. /listings/26) page it crashes with the following error.

![image](https://user-images.githubusercontent.com/47557816/91546568-8e0f2480-e91a-11ea-865f-d91652c63de9.png)

event - build page: /listings/[id]
wait  - compiling...
event - compiled successfully
undefined
TypeError: Cannot read property 'id' of undefined
    at Function.getInitialProps (webpack-internal:///./pages/listings/[id].js:60:145)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any help is appreciated

**Comment by szl0144** [comment]
You can check your nginx conf file, if you set HTTP to HTTPS redirect. If you set, please make sure the redirect syntax you write is return 307 https://xxx.xxx.com$request_uri;  rather than return 301.
